name: CI MedSync

on:
  push:
    branches: ["principal"]
  pull_request:
    branches: ["principal"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer backend
        run: |
          cd backend
          npm install

      - name: Lancer backend
        run: |
          cd backend
          nohup node server.js > server.log 2>&1 &
          sleep 5
        shell: bash

      - name: Tester backend
        run: |
          cd backend
          node tests/test-api.js

      - name: Installer frontend
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build
