name: CI MedSync

on:
  push:
    branches: ["principale"]
  pull_request:
    branches: ["principale"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      # Installation backend
      - name: Installer le backend
        run: |
          cd backend
          npm install

      # ðŸš€ LANCER le backend avant les tests
      - name: Lancer le backend
        run: |
          cd backend
          node server.js &
        shell: bash

      # Tests backend
      - name: Tester le backend
        run: |
          cd backend
          node tests/test-api.js

      # Installation frontend
      - name: Installer le frontend
        run: |
          cd frontend
          npm install

      - name: Build du frontend
        run: |
          cd frontend
          npm run build
